"""Generate src/glyphs.rs: the 8x16 bitmap of every glyph ASCII art can use,
rendered from the bundled PxPlus IBM VGA font. ASCII art matches picture
cells against these shapes, so they must be the face's real pixels.

    python scripts/gen-glyphs.py      (needs Pillow)
"""
import os

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = ImageFont.truetype(os.path.join(ROOT, "assets", "fonts", "PxPlus_IBM_VGA_8x16.ttf"), 16)

CANDIDATES = (
    "".join(chr(c) for c in range(0x20, 0x7F))  # printable ASCII
    + "ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ¢£¥ƒáíóúñÑªº¿¡«»"  # CP437 accents and marks
    + "─│┌┐└┘├┤┬┴┼═║╔╗╚╝╠╣╦╩╬╒╕╘╛╓╖╙╜╞╡╤╧╟╢╥╨╪╫"  # box drawing
    + "░▒▓█▀▄▌▐■▪"  # blocks
    + "αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²"  # CP437 Greek and maths
    + "☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼⌂"  # CP437 symbols
)


def bitmap(ch):
    img = Image.new("L", (8, 16), 0)
    ImageDraw.Draw(img).text((0, 0), ch, font=FONT, fill=255, anchor="la")
    px = img.load()
    return [sum(1 << (7 - x) for x in range(8) if px[x, y] > 127) for y in range(16)]


missing = bitmap("一")  # a CJK ideograph: the face's .notdef box
rows = []
for ch in dict.fromkeys(CANDIDATES):
    b = bitmap(ch)
    if ch != " " and (b == missing or not any(b)):
        continue
    rows.append((ch, b))

out = [
    "//! Generated by `scripts/gen-glyphs.py` from the bundled PxPlus IBM VGA",
    "//! 8x16 font (CC BY-SA 4.0, see assets/fonts). Do not edit by hand.",
    "//!",
    "//! Every glyph ASCII art may set, as its 16 pixel rows (bit 7 = leftmost",
    "//! pixel). `ascii::art_fit` matches picture cells against these shapes.",
    "",
    "pub(crate) static GLYPHS: &[(char, [u8; 16])] = &[",
]
for ch, b in rows:
    lit = "'\\\\'" if ch == "\\" else "'\\''" if ch == "'" else f"'{ch}'"
    out.append(f"    ({lit}, [{', '.join(str(v) for v in b)}]),")
out.append("];")
with open(os.path.join(ROOT, "src", "glyphs.rs"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print(f"{len(rows)} glyphs")
