//! Ordered (Bayer) dithering, the Ferrite texture.
//!
//! A dither field maps every point of an element to a level in `0.0..=1.0`;
//! each cell is inked if its level beats the 4×4 Bayer threshold at that
//! cell. The result is the classic cross-hatched ramp from 1-bit graphics,
//! and it is how Ferrite does what other systems do with gradients, shadows
//! and translucency: there are no gradients in Ferrite, only dither.
//!
//! **Patterns** ([`Pattern`]): `Bayer4` is the texture and the default.
//! `BlueNoise` is also ordered — stable, cacheable, safe to step through for
//! motion — but grid-free, an organic grain. `Atkinson` is error diffusion:
//! each cell depends on the ones before it, so the pattern reshuffles when
//! the size changes and worms across flat fields. It is for [`Picture`]s
//! (the default there), never for structural texture or anything animated.
//!
//! **Where it goes** (structural accents, not noise):
//! panel-header fills, empty states, progress edges, loading placeholders,
//! large backgrounds behind content-free areas. **Never** behind text a user
//! has to read, and never animated continuously.
//!
//! **Device pixels.** Cells are sized in *physical* pixels and the grid is
//! snapped to the device, so a 1-px dither stays a 1-px dither at 125% and
//! 150% instead of smearing into grey mush.
//!
//! **Cost.** A dither is rasterised once into an image at device resolution
//! and cached by (field, size, scale, colors); every later frame paints that
//! image as a single textured quad. Painting cells as individual quads looks
//! the same but costs tens of thousands of quads per element per frame —
//! enough to peg a core (see PITFALLS §17). Fields are therefore plain data
//! ([`Field`]), not closures, so they can be cache keys.

use std::hash::{DefaultHasher, Hash, Hasher};
use std::sync::Arc;

use gpui::{
    App, Bounds, Hsla, IntoElement, Pixels, RenderOnce, StyleRefinement, Styled, Window, canvas,
};

use crate::raster::{self, bgra};

/// The 4×4 Bayer matrix. Thresholds are `(m + 0.5) / 16`.
pub const BAYER4: [[u8; 4]; 4] = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]];

/// The threshold a level must exceed for cell `(x, y)` to be inked.
pub fn threshold(x: u32, y: u32) -> f32 {
    (BAYER4[(y % 4) as usize][(x % 4) as usize] as f32 + 0.5) / 16.0
}

/// Whether cell `(x, y)` is inked at `level`.
pub fn ink(x: u32, y: u32, level: f32) -> bool {
    level > threshold(x, y)
}

/// Side of the blue-noise tile, in cells. It repeats seamlessly.
pub const BLUE_NOISE_SIDE: u32 = 64;

/// A 64×64 void-and-cluster rank tile: every cell's rank 0..4096 as u16 LE.
/// Generated by `regenerate_blue_noise` in this file's tests; not third-party.
static BLUE_NOISE: &[u8] = include_bytes!("../assets/dither/blue-noise-64.bin");

/// The blue-noise threshold for cell `(x, y)`, like [`threshold`] for Bayer.
pub fn blue_noise_threshold(x: u32, y: u32) -> f32 {
    let i = (((y % BLUE_NOISE_SIDE) * BLUE_NOISE_SIDE + x % BLUE_NOISE_SIDE) * 2) as usize;
    (u16::from_le_bytes([BLUE_NOISE[i], BLUE_NOISE[i + 1]]) as f32 + 0.5) / 4096.0
}

/// How a level becomes ink.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Pattern {
    /// 4×4 ordered dither: the cross-hatched Ferrite texture. Fields' default.
    Bayer4,
    /// Ordered dither over a blue-noise tile: an even, grid-free grain.
    /// Behaves exactly like `Bayer4` (stable, cacheable, steppable).
    BlueNoise,
    /// Atkinson error diffusion: crisp, high-contrast, blown highlights — the
    /// 1984 Mac look. Pictures' default. Never for texture or motion.
    Atkinson,
}

/// Atkinson's kernel: 1/8 of the error to each of six neighbours, so 2/8 is
/// thrown away. That loss is the look.
const ATKINSON: [(isize, usize); 6] = [(1, 0), (2, 0), (-1, 1), (0, 1), (1, 1), (0, 2)];

/// Which of `cols`×`rows` cells are inked, row-major, for per-cell `levels`.
pub fn mask(pattern: Pattern, cols: u32, rows: u32, levels: &[f32]) -> Vec<bool> {
    let (c, r) = (cols as usize, rows as usize);
    debug_assert_eq!(levels.len(), c * r);
    match pattern {
        Pattern::Bayer4 | Pattern::BlueNoise => {
            let t = if pattern == Pattern::Bayer4 { threshold } else { blue_noise_threshold };
            (0..r)
                .flat_map(|y| (0..c).map(move |x| (x, y)))
                .map(|(x, y)| levels[y * c + x] > t(x as u32, y as u32))
                .collect()
        }
        Pattern::Atkinson => {
            let mut level = levels.to_vec();
            let mut out = vec![false; c * r];
            for y in 0..r {
                for x in 0..c {
                    let i = y * c + x;
                    let on = level[i] > 0.5;
                    out[i] = on;
                    let err = (level[i] - if on { 1.0 } else { 0.0 }) / 8.0;
                    for (dx, dy) in ATKINSON {
                        let (nx, ny) = (x as isize + dx, y + dy);
                        if nx >= 0 && (nx as usize) < c && ny < r {
                            level[ny * c + nx as usize] += err;
                        }
                    }
                }
            }
            out
        }
    }
}

/// The levels Ferrite uses. Pick from these rather than inventing values so
/// textures match across apps; they map to the CP437 shades `░ ▒ ▓`.
pub mod level {
    pub const LIGHT: f32 = 0.25; // ░
    pub const MEDIUM: f32 = 0.5; // ▒
    pub const DARK: f32 = 0.75; // ▓
}

/// What level each point of an element gets. Coordinates are normalised:
/// `u` runs 0→1 left to right, `v` 0→1 top to bottom.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Field {
    /// Uniform level.
    Flat(f32),
    /// Linear ramp left → right.
    Horizontal { from: f32, to: f32 },
    /// Linear ramp top → bottom.
    Vertical { from: f32, to: f32 },
    /// Falloff from the centre (`center`) to the corners (`edge`).
    Radial { center: f32, edge: f32 },
}

impl Field {
    pub fn level(&self, u: f32, v: f32) -> f32 {
        match *self {
            Field::Flat(l) => l,
            Field::Horizontal { from, to } => from + (to - from) * u,
            Field::Vertical { from, to } => from + (to - from) * v,
            Field::Radial { center, edge } => {
                let (dx, dy) = (u - 0.5, v - 0.5);
                let d = ((dx * dx + dy * dy).sqrt() / std::f32::consts::FRAC_1_SQRT_2).min(1.0);
                center + (edge - center) * d
            }
        }
    }

    fn key(&self) -> [u32; 3] {
        match *self {
            Field::Flat(l) => [0, l.to_bits(), 0],
            Field::Horizontal { from, to } => [1, from.to_bits(), to.to_bits()],
            Field::Vertical { from, to } => [2, from.to_bits(), to.to_bits()],
            Field::Radial { center, edge } => [3, center.to_bits(), edge.to_bits()],
        }
    }
}

pub fn flat(level: f32) -> Field {
    Field::Flat(level)
}

pub fn horizontal(from: f32, to: f32) -> Field {
    Field::Horizontal { from, to }
}

pub fn vertical(from: f32, to: f32) -> Field {
    Field::Vertical { from, to }
}

pub fn radial(center: f32, edge: f32) -> Field {
    Field::Radial { center, edge }
}

/// A grayscale picture to dither: `w`×`h` levels, row-major, 0 = paper and
/// 255 = full ink. It is stretched over the element (bilinear), so size the
/// element to the picture's aspect.
#[derive(Debug, Clone)]
pub struct Picture {
    w: u32,
    h: u32,
    levels: Arc<[u8]>,
    id: u64,
}

impl Picture {
    pub fn new(w: u32, h: u32, levels: Vec<u8>) -> Self {
        assert_eq!(levels.len(), (w * h) as usize, "picture is w×h levels");
        let mut hasher = DefaultHasher::new();
        (w, h, &levels).hash(&mut hasher);
        Picture { w, h, levels: levels.into(), id: hasher.finish() }
    }

    /// Render `f(u, v) -> level` at `w`×`h`; `u`, `v` run 0→1.
    pub fn from_fn(w: u32, h: u32, f: impl Fn(f32, f32) -> f32) -> Self {
        let levels = (0..h)
            .flat_map(|y| (0..w).map(move |x| (x, y)))
            .map(|(x, y)| {
                let (u, v) = ((x as f32 + 0.5) / w as f32, (y as f32 + 0.5) / h as f32);
                (f(u, v).clamp(0.0, 1.0) * 255.0).round() as u8
            })
            .collect();
        Picture::new(w, h, levels)
    }

    fn level(&self, u: f32, v: f32) -> f32 {
        let fx = (u * self.w as f32 - 0.5).clamp(0.0, (self.w - 1) as f32);
        let fy = (v * self.h as f32 - 0.5).clamp(0.0, (self.h - 1) as f32);
        let (x0, y0) = (fx as u32, fy as u32);
        let (x1, y1) = ((x0 + 1).min(self.w - 1), (y0 + 1).min(self.h - 1));
        let at = |x: u32, y: u32| self.levels[(y * self.w + x) as usize] as f32 / 255.0;
        let (tx, ty) = (fx - x0 as f32, fy - y0 as f32);
        let top = at(x0, y0) + (at(x1, y0) - at(x0, y0)) * tx;
        let bottom = at(x0, y1) + (at(x1, y1) - at(x0, y1)) * tx;
        top + (bottom - top) * ty
    }
}

/// What a [`Dither`] draws: a synthetic [`Field`] or a [`Picture`].
#[derive(Debug, Clone)]
pub enum Source {
    Field(Field),
    Picture(Picture),
}

impl From<Field> for Source {
    fn from(field: Field) -> Self {
        Source::Field(field)
    }
}

impl From<Picture> for Source {
    fn from(picture: Picture) -> Self {
        Source::Picture(picture)
    }
}

impl Source {
    fn level(&self, u: f32, v: f32) -> f32 {
        match self {
            Source::Field(field) => field.level(u, v),
            Source::Picture(picture) => picture.level(u, v),
        }
    }

    fn key(&self) -> [u64; 2] {
        match self {
            Source::Field(field) => {
                let [tag, a, b] = field.key();
                [tag as u64, (a as u64) << 32 | b as u64]
            }
            Source::Picture(picture) => [u64::MAX, picture.id],
        }
    }

    fn default_pattern(&self) -> Pattern {
        match self {
            Source::Field(_) => Pattern::Bayer4,
            Source::Picture(_) => Pattern::Atkinson,
        }
    }
}

/// Rasterise `field` into a BGRA buffer `w`×`h` device pixels, with square
/// cells `cell` device pixels on a side, in the Bayer texture. Pure, so it is
/// testable.
pub fn raster(field: Field, w: u32, h: u32, cell: u32, ink_bgra: [u8; 4], paper_bgra: [u8; 4]) -> Vec<u8> {
    raster_source(&Source::Field(field), Pattern::Bayer4, w, h, cell, ink_bgra, paper_bgra)
}

/// [`raster`] for any source and pattern.
pub fn raster_source(source: &Source, pattern: Pattern, w: u32, h: u32, cell: u32, ink_bgra: [u8; 4], paper_bgra: [u8; 4]) -> Vec<u8> {
    let cell = cell.max(1);
    let (cols, rows) = (w.div_ceil(cell), h.div_ceil(cell));
    let levels: Vec<f32> = (0..rows)
        .flat_map(|row| (0..cols).map(move |col| (col, row)))
        .map(|(col, row)| {
            let u = ((col as f32 + 0.5) * cell as f32) / w.max(1) as f32;
            let v = ((row as f32 + 0.5) * cell as f32) / h.max(1) as f32;
            source.level(u, v)
        })
        .collect();
    let mask = mask(pattern, cols, rows, &levels);
    let mut out = vec![0u8; (w * h * 4) as usize];
    for y in 0..h {
        let row_mask = &mask[((y / cell) * cols) as usize..][..cols as usize];
        let line = &mut out[(y * w * 4) as usize..((y + 1) * w * 4) as usize];
        for (x, px) in line.chunks_exact_mut(4).enumerate() {
            px.copy_from_slice(if row_mask[x / cell as usize] { &ink_bgra } else { &paper_bgra });
        }
    }
    out
}

// ── The element ──────────────────────────────────────────────────────────

/// A dithered fill. Size it like any element (`.size_full()`, `.h(px(16.))`).
#[derive(IntoElement)]
pub struct Dither {
    source: Source,
    pattern: Option<Pattern>,
    ink: Option<Hsla>,
    paper: Option<Hsla>,
    cell: u32,
    style: StyleRefinement,
}

/// Start a dither over a [`Field`] or a [`Picture`]. Ink defaults to the
/// palette's `line_strong`.
pub fn dither(source: impl Into<Source>) -> Dither {
    Dither { source: source.into(), pattern: None, ink: None, paper: None, cell: 2, style: StyleRefinement::default() }
}

impl Dither {
    /// The color of inked cells.
    pub fn ink(mut self, color: Hsla) -> Self {
        self.ink = Some(color);
        self
    }

    /// Fill uninked cells too (default: transparent).
    pub fn paper(mut self, color: Hsla) -> Self {
        self.paper = Some(color);
        self
    }

    /// How levels become ink. Defaults: `Bayer4` for fields, `Atkinson` for
    /// pictures.
    pub fn pattern(mut self, pattern: Pattern) -> Self {
        self.pattern = Some(pattern);
        self
    }

    /// Cell edge in **device** pixels. 1 = finest, 2 = default, 3–4 = chunky.
    pub fn cell(mut self, device_px: u32) -> Self {
        self.cell = device_px.max(1);
        self
    }
}

impl Styled for Dither {
    fn style(&mut self) -> &mut StyleRefinement {
        &mut self.style
    }
}

/// Larger than any sane element; guards against a runaway layout asking for
/// a gigapixel texture.
const MAX_SIDE: u32 = 8192;

/// Paint `field` over `bounds` from inside another element's paint — the
/// [`Dither`] element's own path (device-snapped, cached, one quad). Charts
/// use it under a content mask to dither an area under a line: the pattern
/// stays anchored to `bounds`, so clipped pieces line up.
pub(crate) fn paint_field(field: Field, bounds: Bounds<Pixels>, ink: Hsla, window: &mut Window) {
    let sf = window.scale_factor();
    let ox = (f32::from(bounds.origin.x) * sf).round();
    let oy = (f32::from(bounds.origin.y) * sf).round();
    let w = ((f32::from(bounds.size.width) * sf).round() as u32).min(MAX_SIDE);
    let h = ((f32::from(bounds.size.height) * sf).round() as u32).min(MAX_SIDE);
    if w == 0 || h == 0 {
        return;
    }
    let (ink, paper, cell, pattern) = (bgra(ink), [0, 0, 0, 0], 2, Pattern::Bayer4);
    let source = Source::Field(field);
    let key = raster::Key::Dither { source: source.key(), pattern, w, h, cell, ink, paper };
    let image = raster::image(key, window, || (w, h, raster_source(&source, pattern, w, h, cell, ink, paper)));
    raster::paint(image, ox / sf, oy / sf, w, h, window);
}

impl RenderOnce for Dither {
    fn render(self, _window: &mut Window, cx: &mut App) -> impl IntoElement {
        let ink_color = self
            .ink
            .unwrap_or_else(|| crate::tokens::hsla(crate::theme::palette(cx).line_strong));
        let ink = bgra(ink_color);
        let paper = self.paper.map(bgra).unwrap_or([0, 0, 0, 0]);
        let pattern = self.pattern.unwrap_or_else(|| self.source.default_pattern());
        let source = self.source;
        let cell = self.cell;

        let mut element = canvas(
            |_, _, _| {},
            move |bounds: Bounds<Pixels>, _, window: &mut Window, _cx| {
                let sf = window.scale_factor();
                // Snap to the device grid so image pixels map 1:1 onto
                // screen pixels (no resampling blur).
                let ox = (f32::from(bounds.origin.x) * sf).round();
                let oy = (f32::from(bounds.origin.y) * sf).round();
                let w = ((f32::from(bounds.size.width) * sf).round() as u32).min(MAX_SIDE);
                let h = ((f32::from(bounds.size.height) * sf).round() as u32).min(MAX_SIDE);
                if w == 0 || h == 0 {
                    return;
                }
                let key = raster::Key::Dither { source: source.key(), pattern, w, h, cell, ink, paper };
                let image = raster::image(key, window, || (w, h, raster_source(&source, pattern, w, h, cell, ink, paper)));
                raster::paint(image, ox / sf, oy / sf, w, h, window);
            },
        );
        *element.style() = self.style;
        element
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn levels_ink_the_expected_fraction() {
        for (level, expected) in [(0.0, 0), (level::LIGHT, 4), (level::MEDIUM, 8), (level::DARK, 12), (1.0, 16)] {
            let n = (0..4).flat_map(|y| (0..4).map(move |x| (x, y))).filter(|&(x, y)| ink(x, y, level)).count();
            assert_eq!(n, expected, "level {level}");
        }
    }

    #[test]
    fn raster_matches_the_cell_rule() {
        let (ink_px, paper_px) = ([1, 2, 3, 255], [0, 0, 0, 0]);
        // 8×8 device px, 2px cells → a 4×4 cell grid at 50%: half inked.
        let buf = raster(flat(level::MEDIUM), 8, 8, 2, ink_px, paper_px);
        let inked = buf.chunks_exact(4).filter(|p| *p == ink_px).count();
        assert_eq!(inked, 32);
        // Every 2×2 block is uniform.
        for cy in 0..4 {
            for cx in 0..4 {
                let at = |x: u32, y: u32| &buf[((y * 8 + x) * 4) as usize..][..4];
                let first = at(cx * 2, cy * 2);
                for (dx, dy) in [(1, 0), (0, 1), (1, 1)] {
                    assert_eq!(at(cx * 2 + dx, cy * 2 + dy), first);
                }
            }
        }
    }

    #[test]
    fn raster_handles_partial_edge_cells() {
        // Sizes that aren't a multiple of the cell must not panic or overrun.
        let buf = raster(horizontal(0.0, 1.0), 7, 5, 3, [9; 4], [0; 4]);
        assert_eq!(buf.len(), 7 * 5 * 4);
    }

    /// Void-and-cluster (Ulichney, 1993) on an `n`×`n` torus: ranks every
    /// cell 0..n² so that the first k cells, for any k, are spread as evenly
    /// as possible — blue noise. Deterministic for a given seed.
    fn void_and_cluster(n: usize, sigma: f32, seed: u64) -> Vec<u16> {
        let len = n * n;
        // Gaussian weight for each toroidal offset.
        let kernel: Vec<f32> = (0..len)
            .map(|i| {
                let (dx, dy) = (i % n, i / n);
                let (x, y) = (dx.min(n - dx) as f32, dy.min(n - dy) as f32);
                (-(x * x + y * y) / (2.0 * sigma * sigma)).exp()
            })
            .collect();
        let toggle = |on: &mut [bool], energy: &mut [f32], i: usize, set: bool| {
            on[i] = set;
            let sign = if set { 1.0 } else { -1.0 };
            let (ix, iy) = (i % n, i / n);
            for y in 0..n {
                for x in 0..n {
                    energy[y * n + x] += sign * kernel[((y + n - iy) % n) * n + (x + n - ix) % n];
                }
            }
        };
        let tightest = |on: &[bool], energy: &[f32]| (0..len).filter(|&i| on[i]).max_by(|&a, &b| energy[a].total_cmp(&energy[b])).unwrap();
        let largest_void = |on: &[bool], energy: &[f32]| (0..len).filter(|&i| !on[i]).min_by(|&a, &b| energy[a].total_cmp(&energy[b])).unwrap();

        let (mut on, mut energy) = (vec![false; len], vec![0.0f32; len]);
        let mut state = seed;
        let ones = len / 10;
        let mut placed = 0;
        while placed < ones {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            let i = (state % len as u64) as usize;
            if !on[i] {
                toggle(&mut on, &mut energy, i, true);
                placed += 1;
            }
        }
        // Relax the random seed: move the tightest point to the largest void
        // until that is a no-op.
        loop {
            let cluster = tightest(&on, &energy);
            toggle(&mut on, &mut energy, cluster, false);
            let void = largest_void(&on, &energy);
            toggle(&mut on, &mut energy, void, true);
            if void == cluster {
                break;
            }
        }
        let mut rank = vec![0u16; len];
        let (proto_on, proto_energy) = (on.clone(), energy.clone());
        for r in (0..ones).rev() {
            let cluster = tightest(&on, &energy);
            toggle(&mut on, &mut energy, cluster, false);
            rank[cluster] = r as u16;
        }
        // Filling the largest void is also the tightest cluster of the
        // inverted pattern, so this one loop covers both upper phases.
        let (mut on, mut energy) = (proto_on, proto_energy);
        for r in ones..len {
            let void = largest_void(&on, &energy);
            toggle(&mut on, &mut energy, void, true);
            rank[void] = r as u16;
        }
        rank
    }

    /// Writes `assets/dither/blue-noise-64.bin`. Run when changing the
    /// generator: `cargo test --release regenerate_blue_noise -- --ignored`.
    #[test]
    #[ignore]
    fn regenerate_blue_noise() {
        let ranks = void_and_cluster(BLUE_NOISE_SIDE as usize, 1.5, 0x005E_EDF3_2026);
        let bytes: Vec<u8> = ranks.iter().flat_map(|r| r.to_le_bytes()).collect();
        std::fs::write(concat!(env!("CARGO_MANIFEST_DIR"), "/assets/dither/blue-noise-64.bin"), bytes).unwrap();
    }

    #[test]
    fn blue_noise_tile_is_a_full_ranking() {
        let side = BLUE_NOISE_SIDE as usize;
        let mut seen = vec![false; side * side];
        for i in 0..side * side {
            let rank = u16::from_le_bytes([BLUE_NOISE[2 * i], BLUE_NOISE[2 * i + 1]]) as usize;
            assert!(!seen[rank], "rank {rank} appears twice");
            seen[rank] = true;
        }
    }

    #[test]
    fn blue_noise_is_even_at_every_level() {
        // Blue noise has no clumps or holes: at each level every 8×8 window
        // holds close to its share of ink. A white-noise tile fails this.
        let side = BLUE_NOISE_SIDE;
        for level in [level::LIGHT, level::MEDIUM, level::DARK] {
            let expected = level * 64.0;
            for wy in (0..side).step_by(8) {
                for wx in (0..side).step_by(8) {
                    let n = (0..64).filter(|i| level > blue_noise_threshold(wx + i % 8, wy + i / 8)).count() as f32;
                    assert!((n - expected).abs() <= 8.0, "window ({wx},{wy}) at {level}: {n} vs {expected}");
                }
            }
        }
    }

    #[test]
    fn ordered_patterns_ink_the_exact_share() {
        let side = BLUE_NOISE_SIDE;
        let levels = vec![level::LIGHT; (side * side) as usize];
        let inked = mask(Pattern::BlueNoise, side, side, &levels).iter().filter(|&&b| b).count();
        assert_eq!(inked, (side * side / 4) as usize);
    }

    #[test]
    fn atkinson_expands_contrast_and_saturates() {
        // Atkinson drops 2/8 of the error, so tones move away from the middle:
        // a light field inks less than its level, a dark one more. That is
        // the look, not a bug — but it must stay ordered and bounded.
        let (c, r) = (64, 64);
        let share = |level: f32| {
            let inked = mask(Pattern::Atkinson, c, r, &vec![level; (c * r) as usize]).iter().filter(|&&b| b).count();
            inked as f32 / (c * r) as f32
        };
        let (light, medium, dark) = (share(level::LIGHT), share(level::MEDIUM), share(level::DARK));
        assert!(light < level::LIGHT && light > level::LIGHT - 0.12, "light {light}");
        assert!(dark > level::DARK && dark < level::DARK + 0.12, "dark {dark}");
        assert!((medium - 0.5).abs() < 0.06, "medium {medium}");
        assert_eq!(share(0.0), 0.0);
        assert_eq!(share(1.0), 1.0);
    }

    #[test]
    fn pictures_raster_in_every_pattern() {
        let picture = Picture::from_fn(16, 9, |u, v| u * v);
        for pattern in [Pattern::Bayer4, Pattern::BlueNoise, Pattern::Atkinson] {
            let buf = raster_source(&picture.clone().into(), pattern, 37, 21, 3, [9; 4], [0; 4]);
            assert_eq!(buf.len(), 37 * 21 * 4);
        }
    }
}
